version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
    ports:
      - "80:80"

networks:
  wp_network:
    external: true 
